### ISSUE TITLE
Property based testing

### ISSUE THREAD

**Issue by HonzaMac** [tkjn/phprandom#1]
Hi,

this should much more better for testing

fsharpforfunandprofit.com/posts/property-based-testing/

there is several implementations in php to use property check.

Cheers

**Comment by tkjn** [comment]
I appreciate you taking the time to comment. Sorry for talking so long to respond, I fell out with mt_rand and ended up putting this on a back burner for a while.

It sounds like a good idea, I'll have a look into some property-based testing implementations and see how I can apply it for random number generation.
